# -*- coding: utf-8 -*-
"""projeto ecommerce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOsscFh9JpKLLsugzmMp-o5Hl7ngNetV
"""

!pip install boto3

import boto3
S3_ENDPOINT_URL = "https://opgqdbhchfkwcizauknm.storage.supabase.co/storage/v1/s3"
AWS_REGION = "sa-east-1"
AWS_ACCESS_KEY_ID = "8252bea7e6f25218e1b9391bfa0777e3"
AWS_SECRET_ACCESS_KEY = "b4be9ea0f8e658e0fa307baa62517bd15caa94d250ee849dd1a8ed831f99863a"
BUCKET_NAME = "datalake"


s3 = boto3.client(
    "s3",
    region_name=AWS_REGION,
    endpoint_url=S3_ENDPOINT_URL,
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
)

response = s3.list_objects(Bucket=BUCKET_NAME)
arquivos = [obj["Key"] for obj in response["Contents"]]
print(arquivos)

!pip install pandas

import pandas as pd
import io

FILE_KEY = 'preco_competidores.parquet'
response = s3.get_object(Bucket=BUCKET_NAME, Key=FILE_KEY)
parquet_bytes = response["Body"].read()
parquet = io.BytesIO(parquet_bytes)
dataframe = pd.read_parquet(parquet)

!pip install sqlalchemy

from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres.opgqdbhchfkwcizauknm:capitaorex501@aws-1-sa-east-1.pooler.supabase.com:5432/postgres"
engine = create_engine(DATABASE_URL)

dataframe.to_sql("preco_competidores", engine, if_exists="replace", index=False)